language: ruby
rvm:
 - 2.2.1
env:
  - DB=mysql
before_install:
  - cd ecosense
  - gem install bundler
  - gem install rails
  - gem install byebug
before_script:
  - bundle install
  - bundle exec rake db:create db:schema:load --trace
script:
  - RAILS_ENV=test bundle exec rake db:migrate test